### ISSUE TITLE
ilp32 image cannot boot on CamRV-K230 board

### ISSUE THREAD

**Issue by Ruinland** [ruyisdk/mkimg-k230-rv64ilp32#2]
Hi ,

I am facing boot failure with the released image for ilp32:
https://github.com/ruyisdk/mkimg-k230-rv64ilp32/releases/download/2024.03.13-128m/k230-sdcard-fedora_rv32-evb-rv64ilp32.img.zst

This image is mentioned in Fedora wiki :
https://fedoraproject.org/w/index.php?title=Architectures/RISC-V/64ILP32

Yet I cannot boot the image on K230 with the SD card flashed with the image above.
The U-boot (or FSBL) will fail in a very early stage.
Is there any write-up or manual that I can follow step-by-step ?

Thanks in advance,
Ruinland

**Comment by U2FsdGVkX1** [comment]
Do you have a log please?

**Comment by Ruinland** [comment]
@U2FsdGVkX1 

```
▒1+-!!!!1c
U-Boot SPL 2022.10-g05c93ec8 (Mar 03 2024 - 11:33:01 +0000)
00000000: PMU Major Msg: End of CA training                                                                                                                                                                                                  
00000000: PMU Major Msg: End of initialization                                                                                                                                                                                               
00000000: PMU Major Msg: End of read enable training                                                                                                                                                                                         
00000000: PMU Major Msg: End of fine write leveling                                                                                                                                                                                          
00000000: PMU Major Msg: End of read dq deskew training                                                                                                                                                                                      
00000000: PMU Major Msg: End of MPR read delay center optimization                                                                                                                                                                           
00000000: PMU Major Msg: End of Write leveling coarse delay                                                                                                                                                                                  
00000000: PMU Major Msg: End of write delay center optimization                                                                                                                                                                              
00000000: PMU Major Msg: End of read delay center optimization                                                                                                                                                                               
00000000: PMU Major Msg: End of max read latency training                                                                                                                                                                                    
00000000: PMU Major Msg: Firmware run has completed                                                                                                                                                                                          
sha256 error uboot boot failed
spl_board_init_f() failed: -3

reboot system
```

Steps to reproduce : 

1. Download the [image](Download the https://github.com/ruyisdk/mkimg-k230-rv64ilp32/releases/download/2024.03.13-128m/k230-sdcard-fedora_rv32-evb-rv64ilp32.img.zst) from release page.
2. `unzstd k230-sdcard-fedora_rv32-evb-rv64ilp32.img.zst` 
3. `dd if=k230-sdcard-fedora_rv32-evb-rv64ilp32.img of=/dev/sdb bs=1M conv=fsync status=progress`
4. Plug USB type-c cable to PC and fireup putty with baud rate as `115200`
5. The log above is shown.

I have tested the images with 2 boards. They are not working.
I tested the K230 image from Kendryte, the system boots.
Therefore, I think the images here requires some special treatment.

**Comment by U2FsdGVkX1** [comment]
> @U2FsdGVkX1
> 
> ```
> ▒1+-!!!!1c
> U-Boot SPL 2022.10-g05c93ec8 (Mar 03 2024 - 11:33:01 +0000)
> 00000000: PMU Major Msg: End of CA training                                                                                                                                                                                                  
> 00000000: PMU Major Msg: End of initialization                                                                                                                                                                                               
> 00000000: PMU Major Msg: End of read enable training                                                                                                                                                                                         
> 00000000: PMU Major Msg: End of fine write leveling                                                                                                                                                                                          
> 00000000: PMU Major Msg: End of read dq deskew training                                                                                                                                                                                      
> 00000000: PMU Major Msg: End of MPR read delay center optimization                                                                                                                                                                           
> 00000000: PMU Major Msg: End of Write leveling coarse delay                                                                                                                                                                                  
> 00000000: PMU Major Msg: End of write delay center optimization                                                                                                                                                                              
> 00000000: PMU Major Msg: End of read delay center optimization                                                                                                                                                                               
> 00000000: PMU Major Msg: End of max read latency training                                                                                                                                                                                    
> 00000000: PMU Major Msg: Firmware run has completed                                                                                                                                                                                          
> sha256 error uboot boot failed
> spl_board_init_f() failed: -3
> 
> reboot system
> ```
> 
> Steps to reproduce :
> 
> 1. Download the [image](Download the https://github.com/ruyisdk/mkimg-k230-rv64ilp32/releases/download/2024.03.13-128m/k230-sdcard-fedora_rv32-evb-rv64ilp32.img.zst) from release page.
> 2. `unzstd k230-sdcard-fedora_rv32-evb-rv64ilp32.img.zst`
> 3. `dd if=k230-sdcard-fedora_rv32-evb-rv64ilp32.img of=/dev/sdb bs=1M conv=fsync status=progress`
> 4. Plug USB type-c cable to PC and fireup putty with baud rate as `115200`
> 5. The log above is shown.
> 
> I have tested the images with 2 boards. They are not working. I tested the K230 image from Kendryte, the system boots. Therefore, I think the images here requires some special treatment.

Do you have any other TF cards to test? It looks like sha256 is incorrect.
You can follow these commands

```
wipefs -a /dev/sdb
dd if=k230-sdcard-fedora_rv32-evb-rv64ilp32.img of=/dev/sdb bs=1M conv=fsync status=progress
eject /dev/sdb
```

If it still doesn't work, let me know :)

**Comment by Ruinland** [comment]
Thanks, the wipefs seems to be necessary for ensuring uboot checksum check.
